# /etc/logrotate.d/metanode
# Logrotate configuration for MetaNode logs
# This will be installed to /etc/logrotate.d/metanode automatically by install-services.sh

{{RUST_WORKDIR}}/logs/node_*/rust.log
{{RUST_WORKDIR}}/logs/node_*/go-master-stdout.log
{{RUST_WORKDIR}}/logs/node_*/go-sub-stdout.log
{{GO_WORKDIR}}/cmd/simple_chain/node_logs/*.log
{{GO_WORKDIR}}/cmd/simple_chain/*.log
{
    su {{USER}} {{USER}}
    daily
    rotate 7
    maxsize 500M
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
}
