// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.20.3
// source: state.proto

package mtn_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type STAKE_TYPE int32

const (
	STAKE_TYPE_VALIDATOR     STAKE_TYPE = 0
	STAKE_TYPE_NODE          STAKE_TYPE = 1
	STAKE_TYPE_VERIFY_MINER  STAKE_TYPE = 2
	STAKE_TYPE_EXECUTE_MINER STAKE_TYPE = 3
)

// Enum value maps for STAKE_TYPE.
var (
	STAKE_TYPE_name = map[int32]string{
		0: "VALIDATOR",
		1: "NODE",
		2: "VERIFY_MINER",
		3: "EXECUTE_MINER",
	}
	STAKE_TYPE_value = map[string]int32{
		"VALIDATOR":     0,
		"NODE":          1,
		"VERIFY_MINER":  2,
		"EXECUTE_MINER": 3,
	}
)

func (x STAKE_TYPE) Enum() *STAKE_TYPE {
	p := new(STAKE_TYPE)
	*p = x
	return p
}

func (x STAKE_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (STAKE_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[0].Descriptor()
}

func (STAKE_TYPE) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[0]
}

func (x STAKE_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use STAKE_TYPE.Descriptor instead.
func (STAKE_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

type ACCOUNT_TYPE int32

const (
	ACCOUNT_TYPE_REGULAR_ACCOUNT   ACCOUNT_TYPE = 0
	ACCOUNT_TYPE_READ_WRITE_STRICT ACCOUNT_TYPE = 1
)

// Enum value maps for ACCOUNT_TYPE.
var (
	ACCOUNT_TYPE_name = map[int32]string{
		0: "REGULAR_ACCOUNT",
		1: "READ_WRITE_STRICT",
	}
	ACCOUNT_TYPE_value = map[string]int32{
		"REGULAR_ACCOUNT":   0,
		"READ_WRITE_STRICT": 1,
	}
)

func (x ACCOUNT_TYPE) Enum() *ACCOUNT_TYPE {
	p := new(ACCOUNT_TYPE)
	*p = x
	return p
}

func (x ACCOUNT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ACCOUNT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[1].Descriptor()
}

func (ACCOUNT_TYPE) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[1]
}

func (x ACCOUNT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ACCOUNT_TYPE.Descriptor instead.
func (ACCOUNT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

type UPDATE_STATE_FIELD int32

const (
	UPDATE_STATE_FIELD_ADD_BALANCE     UPDATE_STATE_FIELD = 0
	UPDATE_STATE_FIELD_SUB_BALANCE     UPDATE_STATE_FIELD = 1
	UPDATE_STATE_FIELD_STORAGE_ROOT    UPDATE_STATE_FIELD = 2
	UPDATE_STATE_FIELD_CODE_HASH       UPDATE_STATE_FIELD = 3
	UPDATE_STATE_FIELD_STORAGE_ADDRESS UPDATE_STATE_FIELD = 4
	UPDATE_STATE_FIELD_CREATOR_PUBKEY  UPDATE_STATE_FIELD = 5
	UPDATE_STATE_FIELD_LOGS_HASH       UPDATE_STATE_FIELD = 6
)

// Enum value maps for UPDATE_STATE_FIELD.
var (
	UPDATE_STATE_FIELD_name = map[int32]string{
		0: "ADD_BALANCE",
		1: "SUB_BALANCE",
		2: "STORAGE_ROOT",
		3: "CODE_HASH",
		4: "STORAGE_ADDRESS",
		5: "CREATOR_PUBKEY",
		6: "LOGS_HASH",
	}
	UPDATE_STATE_FIELD_value = map[string]int32{
		"ADD_BALANCE":     0,
		"SUB_BALANCE":     1,
		"STORAGE_ROOT":    2,
		"CODE_HASH":       3,
		"STORAGE_ADDRESS": 4,
		"CREATOR_PUBKEY":  5,
		"LOGS_HASH":       6,
	}
)

func (x UPDATE_STATE_FIELD) Enum() *UPDATE_STATE_FIELD {
	p := new(UPDATE_STATE_FIELD)
	*p = x
	return p
}

func (x UPDATE_STATE_FIELD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UPDATE_STATE_FIELD) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[2].Descriptor()
}

func (UPDATE_STATE_FIELD) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[2]
}

func (x UPDATE_STATE_FIELD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UPDATE_STATE_FIELD.Descriptor instead.
func (UPDATE_STATE_FIELD) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{2}
}

type StateChannelState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidatorAddress [][]byte `protobuf:"bytes,1,rep,name=ValidatorAddress,proto3" json:"ValidatorAddress,omitempty"`
}

func (x *StateChannelState) Reset() {
	*x = StateChannelState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateChannelState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChannelState) ProtoMessage() {}

func (x *StateChannelState) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChannelState.ProtoReflect.Descriptor instead.
func (*StateChannelState) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

func (x *StateChannelState) GetValidatorAddress() [][]byte {
	if x != nil {
		return x.ValidatorAddress
	}
	return nil
}

type AccountState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address            []byte              `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	LastHash           []byte              `protobuf:"bytes,2,opt,name=LastHash,proto3" json:"LastHash,omitempty"`
	Balance            []byte              `protobuf:"bytes,3,opt,name=Balance,proto3" json:"Balance,omitempty"`
	PendingBalance     []byte              `protobuf:"bytes,4,opt,name=PendingBalance,proto3" json:"PendingBalance,omitempty"`
	SmartContractState *SmartContractState `protobuf:"bytes,5,opt,name=SmartContractState,proto3" json:"SmartContractState,omitempty"`
	DeviceKey          []byte              `protobuf:"bytes,6,opt,name=DeviceKey,proto3" json:"DeviceKey,omitempty"`
	Nonce              []byte              `protobuf:"bytes,7,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	PublicKeyBls       []byte              `protobuf:"bytes,8,opt,name=PublicKeyBls,proto3" json:"PublicKeyBls,omitempty"`
	AccountType        ACCOUNT_TYPE        `protobuf:"varint,9,opt,name=AccountType,proto3,enum=account_state.ACCOUNT_TYPE" json:"AccountType,omitempty"` // StateChannelState StateChannelState = 7; // DEPRECATED
}

func (x *AccountState) Reset() {
	*x = AccountState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountState) ProtoMessage() {}

func (x *AccountState) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountState.ProtoReflect.Descriptor instead.
func (*AccountState) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

func (x *AccountState) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AccountState) GetLastHash() []byte {
	if x != nil {
		return x.LastHash
	}
	return nil
}

func (x *AccountState) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *AccountState) GetPendingBalance() []byte {
	if x != nil {
		return x.PendingBalance
	}
	return nil
}

func (x *AccountState) GetSmartContractState() *SmartContractState {
	if x != nil {
		return x.SmartContractState
	}
	return nil
}

func (x *AccountState) GetDeviceKey() []byte {
	if x != nil {
		return x.DeviceKey
	}
	return nil
}

func (x *AccountState) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *AccountState) GetPublicKeyBls() []byte {
	if x != nil {
		return x.PublicKeyBls
	}
	return nil
}

func (x *AccountState) GetAccountType() ACCOUNT_TYPE {
	if x != nil {
		return x.AccountType
	}
	return ACCOUNT_TYPE_REGULAR_ACCOUNT
}

type GetAccountStateWithIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *GetAccountStateWithIdRequest) Reset() {
	*x = GetAccountStateWithIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountStateWithIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountStateWithIdRequest) ProtoMessage() {}

func (x *GetAccountStateWithIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountStateWithIdRequest.ProtoReflect.Descriptor instead.
func (*GetAccountStateWithIdRequest) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountStateWithIdRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *GetAccountStateWithIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AccountStateWithIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountState *AccountState `protobuf:"bytes,1,opt,name=AccountState,proto3" json:"AccountState,omitempty"`
	Id           string        `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *AccountStateWithIdRequest) Reset() {
	*x = AccountStateWithIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountStateWithIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountStateWithIdRequest) ProtoMessage() {}

func (x *AccountStateWithIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountStateWithIdRequest.ProtoReflect.Descriptor instead.
func (*AccountStateWithIdRequest) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{3}
}

func (x *AccountStateWithIdRequest) GetAccountState() *AccountState {
	if x != nil {
		return x.AccountState
	}
	return nil
}

func (x *AccountStateWithIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SmartContractState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatorPublicKey []byte `protobuf:"bytes,1,opt,name=CreatorPublicKey,proto3" json:"CreatorPublicKey,omitempty"`
	CodeHash         []byte `protobuf:"bytes,3,opt,name=CodeHash,proto3" json:"CodeHash,omitempty"`
	StorageRoot      []byte `protobuf:"bytes,4,opt,name=StorageRoot,proto3" json:"StorageRoot,omitempty"`
	StorageAddress   []byte `protobuf:"bytes,7,opt,name=StorageAddress,proto3" json:"StorageAddress,omitempty"`
	// string StorageHost = 2; // host that store smart contract state of account // DEPRECATED
	// repeated bytes RelatedAddresses = 6; // address of smart contract relate to this smart contract, use for parrallel execute // DEPRECATED
	// bytes LockingStateChannel = 8; // address of state channel that lock this smart contract // DEPRECATED
	LogsHash        []byte            `protobuf:"bytes,5,opt,name=LogsHash,proto3" json:"LogsHash,omitempty"` // hash of smart contract state // DEPRECATED
	TrieDatabaseMap map[string][]byte `protobuf:"bytes,9,rep,name=TrieDatabaseMap,proto3" json:"TrieDatabaseMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MapFullDbHash   []byte            `protobuf:"bytes,10,opt,name=MapFullDbHash,proto3" json:"MapFullDbHash,omitempty"`
	SimpleDbHash    []byte            `protobuf:"bytes,11,opt,name=SimpleDbHash,proto3" json:"SimpleDbHash,omitempty"`
}

func (x *SmartContractState) Reset() {
	*x = SmartContractState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmartContractState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartContractState) ProtoMessage() {}

func (x *SmartContractState) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartContractState.ProtoReflect.Descriptor instead.
func (*SmartContractState) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{4}
}

func (x *SmartContractState) GetCreatorPublicKey() []byte {
	if x != nil {
		return x.CreatorPublicKey
	}
	return nil
}

func (x *SmartContractState) GetCodeHash() []byte {
	if x != nil {
		return x.CodeHash
	}
	return nil
}

func (x *SmartContractState) GetStorageRoot() []byte {
	if x != nil {
		return x.StorageRoot
	}
	return nil
}

func (x *SmartContractState) GetStorageAddress() []byte {
	if x != nil {
		return x.StorageAddress
	}
	return nil
}

func (x *SmartContractState) GetLogsHash() []byte {
	if x != nil {
		return x.LogsHash
	}
	return nil
}

func (x *SmartContractState) GetTrieDatabaseMap() map[string][]byte {
	if x != nil {
		return x.TrieDatabaseMap
	}
	return nil
}

func (x *SmartContractState) GetMapFullDbHash() []byte {
	if x != nil {
		return x.MapFullDbHash
	}
	return nil
}

func (x *SmartContractState) GetSimpleDbHash() []byte {
	if x != nil {
		return x.SimpleDbHash
	}
	return nil
}

type StorageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *StorageData) Reset() {
	*x = StorageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageData) ProtoMessage() {}

func (x *StorageData) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageData.ProtoReflect.Descriptor instead.
func (*StorageData) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{5}
}

func (x *StorageData) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StorageData) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type StorageDatas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datas []*StorageData `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
}

func (x *StorageDatas) Reset() {
	*x = StorageDatas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDatas) ProtoMessage() {}

func (x *StorageDatas) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDatas.ProtoReflect.Descriptor instead.
func (*StorageDatas) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{6}
}

func (x *StorageDatas) GetDatas() []*StorageData {
	if x != nil {
		return x.Datas
	}
	return nil
}

type UpdateStateField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field UPDATE_STATE_FIELD `protobuf:"varint,1,opt,name=Field,proto3,enum=account_state.UPDATE_STATE_FIELD" json:"Field,omitempty"`
	Value []byte             `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *UpdateStateField) Reset() {
	*x = UpdateStateField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStateField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStateField) ProtoMessage() {}

func (x *UpdateStateField) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStateField.ProtoReflect.Descriptor instead.
func (*UpdateStateField) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateStateField) GetField() UPDATE_STATE_FIELD {
	if x != nil {
		return x.Field
	}
	return UPDATE_STATE_FIELD_ADD_BALANCE
}

func (x *UpdateStateField) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type UpdateStateFields struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte              `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Fields  []*UpdateStateField `protobuf:"bytes,2,rep,name=Fields,proto3" json:"Fields,omitempty"`
}

func (x *UpdateStateFields) Reset() {
	*x = UpdateStateFields{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStateFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStateFields) ProtoMessage() {}

func (x *UpdateStateFields) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStateFields.ProtoReflect.Descriptor instead.
func (*UpdateStateFields) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateStateFields) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UpdateStateFields) GetFields() []*UpdateStateField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type UpdateStateFieldsListWithBlockNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields      []*UpdateStateFields `protobuf:"bytes,1,rep,name=Fields,proto3" json:"Fields,omitempty"`
	BlockNumber uint64               `protobuf:"varint,2,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
}

func (x *UpdateStateFieldsListWithBlockNumber) Reset() {
	*x = UpdateStateFieldsListWithBlockNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStateFieldsListWithBlockNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStateFieldsListWithBlockNumber) ProtoMessage() {}

func (x *UpdateStateFieldsListWithBlockNumber) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStateFieldsListWithBlockNumber.ProtoReflect.Descriptor instead.
func (*UpdateStateFieldsListWithBlockNumber) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateStateFieldsListWithBlockNumber) GetFields() []*UpdateStateFields {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *UpdateStateFieldsListWithBlockNumber) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type SCStatesWithBlockNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SCStates    map[string]*SmartContractState `protobuf:"bytes,1,rep,name=SCStates,proto3" json:"SCStates,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	BlockNumber uint64                         `protobuf:"varint,2,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
}

func (x *SCStatesWithBlockNumber) Reset() {
	*x = SCStatesWithBlockNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCStatesWithBlockNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCStatesWithBlockNumber) ProtoMessage() {}

func (x *SCStatesWithBlockNumber) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCStatesWithBlockNumber.ProtoReflect.Descriptor instead.
func (*SCStatesWithBlockNumber) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{10}
}

func (x *SCStatesWithBlockNumber) GetSCStates() map[string]*SmartContractState {
	if x != nil {
		return x.SCStates
	}
	return nil
}

func (x *SCStatesWithBlockNumber) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

var File_state_proto protoreflect.FileDescriptor

var file_state_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x3f, 0x0a, 0x11,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x2a, 0x0a, 0x10, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x10, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xf0, 0x02,
	0x0a, 0x0c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x73, 0x74,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x4c, 0x61, 0x73, 0x74,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x12, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x12, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x42, 0x6c, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x42, 0x6c,
	0x73, 0x12, 0x3d, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x48, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0x6c, 0x0a, 0x19, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0xb2, 0x03, 0x0a, 0x12, 0x53, 0x6d, 0x61,
	0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x2a, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x6f, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x43,
	0x6f, 0x64, 0x65, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x43,
	0x6f, 0x64, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x73, 0x48, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x4c, 0x6f, 0x67, 0x73, 0x48, 0x61, 0x73, 0x68, 0x12, 0x60, 0x0a,
	0x0f, 0x54, 0x72, 0x69, 0x65, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x4d, 0x61, 0x70,
	0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x72, 0x69, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f,
	0x54, 0x72, 0x69, 0x65, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x4d, 0x61, 0x70, 0x12,
	0x24, 0x0a, 0x0d, 0x4d, 0x61, 0x70, 0x46, 0x75, 0x6c, 0x6c, 0x44, 0x62, 0x48, 0x61, 0x73, 0x68,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x4d, 0x61, 0x70, 0x46, 0x75, 0x6c, 0x6c, 0x44,
	0x62, 0x48, 0x61, 0x73, 0x68, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x44,
	0x62, 0x48, 0x61, 0x73, 0x68, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x53, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x44, 0x62, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x42, 0x0a, 0x14, 0x54, 0x72, 0x69,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x35, 0x0a,
	0x0b, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03,
	0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x40, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x73, 0x12, 0x30, 0x0a, 0x05, 0x44, 0x61, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x05, 0x44, 0x61, 0x74, 0x61, 0x73, 0x22, 0x61, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x37, 0x0a, 0x05, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x49, 0x45, 0x4c, 0x44, 0x52, 0x05, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x66, 0x0a, 0x11, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x37, 0x0a, 0x06, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x22, 0x82, 0x01, 0x0a, 0x24, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x06, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x06, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0xed, 0x01, 0x0a, 0x17, 0x53, 0x43, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x73, 0x57, 0x69, 0x74, 0x68, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x50, 0x0a, 0x08, 0x53, 0x43, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x43, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x57, 0x69, 0x74,
	0x68, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x53, 0x43, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x53, 0x43, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x5e, 0x0a, 0x0d, 0x53, 0x43, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x37, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x4a, 0x0a, 0x0a, 0x53, 0x54, 0x41, 0x4b, 0x45, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x12, 0x0d, 0x0a, 0x09, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x4f,
	0x52, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x44, 0x45, 0x10, 0x01, 0x12, 0x10, 0x0a,
	0x0c, 0x56, 0x45, 0x52, 0x49, 0x46, 0x59, 0x5f, 0x4d, 0x49, 0x4e, 0x45, 0x52, 0x10, 0x02, 0x12,
	0x11, 0x0a, 0x0d, 0x45, 0x58, 0x45, 0x43, 0x55, 0x54, 0x45, 0x5f, 0x4d, 0x49, 0x4e, 0x45, 0x52,
	0x10, 0x03, 0x2a, 0x3a, 0x0a, 0x0c, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x47, 0x55, 0x4c, 0x41, 0x52, 0x5f, 0x41, 0x43,
	0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x45, 0x41, 0x44, 0x5f,
	0x57, 0x52, 0x49, 0x54, 0x45, 0x5f, 0x53, 0x54, 0x52, 0x49, 0x43, 0x54, 0x10, 0x01, 0x2a, 0x8f,
	0x01, 0x0a, 0x12, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x46, 0x49, 0x45, 0x4c, 0x44, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x44, 0x44, 0x5f, 0x42, 0x41, 0x4c,
	0x41, 0x4e, 0x43, 0x45, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x55, 0x42, 0x5f, 0x42, 0x41,
	0x4c, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x4f, 0x52, 0x41,
	0x47, 0x45, 0x5f, 0x52, 0x4f, 0x4f, 0x54, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x44,
	0x45, 0x5f, 0x48, 0x41, 0x53, 0x48, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x54, 0x4f, 0x52,
	0x41, 0x47, 0x45, 0x5f, 0x41, 0x44, 0x44, 0x52, 0x45, 0x53, 0x53, 0x10, 0x04, 0x12, 0x12, 0x0a,
	0x0e, 0x43, 0x52, 0x45, 0x41, 0x54, 0x4f, 0x52, 0x5f, 0x50, 0x55, 0x42, 0x4b, 0x45, 0x59, 0x10,
	0x05, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x4f, 0x47, 0x53, 0x5f, 0x48, 0x41, 0x53, 0x48, 0x10, 0x06,
	0x42, 0x39, 0x0a, 0x2b, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x6e, 0x6f, 0x64,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65,
	0x64, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5a,
	0x0a, 0x2f, 0x6d, 0x74, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_state_proto_rawDescOnce sync.Once
	file_state_proto_rawDescData = file_state_proto_rawDesc
)

func file_state_proto_rawDescGZIP() []byte {
	file_state_proto_rawDescOnce.Do(func() {
		file_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_state_proto_rawDescData)
	})
	return file_state_proto_rawDescData
}

var file_state_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_state_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_state_proto_goTypes = []interface{}{
	(STAKE_TYPE)(0),                              // 0: account_state.STAKE_TYPE
	(ACCOUNT_TYPE)(0),                            // 1: account_state.ACCOUNT_TYPE
	(UPDATE_STATE_FIELD)(0),                      // 2: account_state.UPDATE_STATE_FIELD
	(*StateChannelState)(nil),                    // 3: account_state.StateChannelState
	(*AccountState)(nil),                         // 4: account_state.AccountState
	(*GetAccountStateWithIdRequest)(nil),         // 5: account_state.GetAccountStateWithIdRequest
	(*AccountStateWithIdRequest)(nil),            // 6: account_state.AccountStateWithIdRequest
	(*SmartContractState)(nil),                   // 7: account_state.SmartContractState
	(*StorageData)(nil),                          // 8: account_state.StorageData
	(*StorageDatas)(nil),                         // 9: account_state.StorageDatas
	(*UpdateStateField)(nil),                     // 10: account_state.UpdateStateField
	(*UpdateStateFields)(nil),                    // 11: account_state.UpdateStateFields
	(*UpdateStateFieldsListWithBlockNumber)(nil), // 12: account_state.UpdateStateFieldsListWithBlockNumber
	(*SCStatesWithBlockNumber)(nil),              // 13: account_state.SCStatesWithBlockNumber
	nil,                                          // 14: account_state.SmartContractState.TrieDatabaseMapEntry
	nil,                                          // 15: account_state.SCStatesWithBlockNumber.SCStatesEntry
}
var file_state_proto_depIdxs = []int32{
	7,  // 0: account_state.AccountState.SmartContractState:type_name -> account_state.SmartContractState
	1,  // 1: account_state.AccountState.AccountType:type_name -> account_state.ACCOUNT_TYPE
	4,  // 2: account_state.AccountStateWithIdRequest.AccountState:type_name -> account_state.AccountState
	14, // 3: account_state.SmartContractState.TrieDatabaseMap:type_name -> account_state.SmartContractState.TrieDatabaseMapEntry
	8,  // 4: account_state.StorageDatas.Datas:type_name -> account_state.StorageData
	2,  // 5: account_state.UpdateStateField.Field:type_name -> account_state.UPDATE_STATE_FIELD
	10, // 6: account_state.UpdateStateFields.Fields:type_name -> account_state.UpdateStateField
	11, // 7: account_state.UpdateStateFieldsListWithBlockNumber.Fields:type_name -> account_state.UpdateStateFields
	15, // 8: account_state.SCStatesWithBlockNumber.SCStates:type_name -> account_state.SCStatesWithBlockNumber.SCStatesEntry
	7,  // 9: account_state.SCStatesWithBlockNumber.SCStatesEntry.value:type_name -> account_state.SmartContractState
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_state_proto_init() }
func file_state_proto_init() {
	if File_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateChannelState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountStateWithIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountStateWithIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmartContractState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorageDatas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStateField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStateFields); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStateFieldsListWithBlockNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCStatesWithBlockNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_state_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_proto_goTypes,
		DependencyIndexes: file_state_proto_depIdxs,
		EnumInfos:         file_state_proto_enumTypes,
		MessageInfos:      file_state_proto_msgTypes,
	}.Build()
	File_state_proto = out.File
	file_state_proto_rawDesc = nil
	file_state_proto_goTypes = nil
	file_state_proto_depIdxs = nil
}
